### PR TITLE
Added case for '\r'

### PR DESCRIPTION
**Pull request by pczajkowski-ptw**
When trying to parse PO file with strings containing "\r\n" there's an error "Escape sequence is invalid at". But I believe it's a valid case, PO files can also be generated/used on Windows, hence I've added it.

### CODE REVIEW

**Comment by adams85** [comment]
Hi!

Thanks for the suggestion. However, it doesn't seem like a good idea to me. Allowing platform-dependent new lines in PO string literals would complicate new line handling pretty much.

[The specification](https://www.gnu.org/software/gettext/manual/html_node/PO-Files.html) which this library is based on isn't particularly clear on this question. Poedit uses `\n` for new lines even on Windows.

In my opinion, it's better to use a platform-independent encoding for storage and transform the new line characters when loading the file. As a matter of fact, this is already supported: `StringDecodingOptions` provide full control over the new line decoding behavior. (See also this [discussion](https://github.com/adams85/po/issues/9)).

**Comment by pczajkowski-ptw** [comment]
Sorry for replying so late. Unfortunately proposed solution doesn't help in my case and I need to replace "\r\n" with "\\r\\n" in PO file before parsing it via your library. Hence my PR.

**Comment by adams85** [comment]
After giving some more thought to the problem, I came to the conclusion that it's ok to accept other line terminator sequences than `'\n'` during parsing. (This doesn't interfere with `StringDecodingOptions` which determine what newline sequence to use in the decoded strings.) Writing back PO content to file will be done with `'\n'`. This corresponds to the behavior of POEdit.

I'm going to merge this change now and release a new version containing it soon.

**Comment by adams85** [comment]
Version 1.9.0 is now available on NuGet.

**Pull request merged**
