### PR TITLE
Master

### PR DESCRIPTION
**Pull request by GioviQ**
avoiding unexpected token error

### CODE REVIEW

**Comment by adams85** [comment]
PO files are text files and '\0' characters in text files are non-standard as described also in [this SO post](https://stackoverflow.com/questions/30825491/does-0-appear-naturally-in-text-files#answer-30825561):

> However, the NUL byte has no valid reason for existing in a plain text file, and it may be considered at least a de facto standard for text files that they do not contain the NUL byte (or certain other control characters, which might break transmission of that text through some terminals or serial protocols).

Thus, in my opinion, the current behavior is correct. I think it should be the consumer's responsibility to deal with invalid input, not the parser's.

So I won't merge this PR. If you need to have this feature built in the library by any means, I suggest forking it.

**Comment by GioviQ** [comment]
Consider this case:


Bob exports PO files with your library, then he sends po file to translator Alice. Alice returns po file to Bob.

Bob tries to import Alice update po file, but import fails.

Bob is not a developer, open PO file with text editor and he doesn't find any errors, because '\0' at the end are invisible.

Bob says the application doesn't work.

**Comment by adams85** [comment]
By "consumer" I meant the author of the application which consumes the PO library (presumably, _you_), not the consumer of the end product (_Bob_).

If the application has to accept invalid input, the author's responsibility to sanitize it before feeding it to the PO parser. E.g.

```csharp
var content = File.ReadAllText(@"path\to\translation_from_Alice.po");
var sanitizedContent = content.TrimEnd('\0');
var parseResult = new POParser().Parse(sanitizedContent);
// ...
```

Or, if you have to avoid loading the whole PO file upfront, you can implement a customized `Stream` or `StreamReader` which strips the trailing `\0` on the fly.

**Comment by GioviQ** [comment]
So your library demands outside every input validation.

Ok

**Comment by adams85** [comment]
We can say so. Or I'd rather say it assumes valid input. If gets invalid input, it reports that in the form of a diagnostic error.

**Comment by GioviQ** [comment]
> We can say so. Or I'd rather say it assumes valid input. If gets invalid input, it reports that in the form of a diagnostic error.

But diagnostic error in this case is misleading.

**Comment by adams85** [comment]
The diagnostic error may be improved for sure. I've opened an issue for the matter. Would you like to address it?

**Pull request closed without merging**
